# Generated by Django 3.2.8 on 2021-12-05 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='review_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
